// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtYJ5qIuL_BafjKXZpn8A8U7dLFYg1n28',
    appId: '1:183514899423:web:edc316f3763b0c365e9a6a',
    messagingSenderId: '183514899423',
    projectId: 'taksikapim',
    authDomain: 'taksikapim.firebaseapp.com',
    databaseURL: 'https://taksikapim-default-rtdb.firebaseio.com',
    storageBucket: 'taksikapim.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW0oiv-lR2tC6y_-kirAjWLBDQ01FLCoo',
    appId: '1:183514899423:android:eb2418de2a5ab04b5e9a6a',
    messagingSenderId: '183514899423',
    projectId: 'taksikapim',
    databaseURL: 'https://taksikapim-default-rtdb.firebaseio.com',
    storageBucket: 'taksikapim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj3R1ZeEdyxEr-5us6NdAiK0IyvhjHQeE',
    appId: '1:183514899423:ios:ee4bebddca1207295e9a6a',
    messagingSenderId: '183514899423',
    projectId: 'taksikapim',
    databaseURL: 'https://taksikapim-default-rtdb.firebaseio.com',
    storageBucket: 'taksikapim.firebasestorage.app',
    iosBundleId: 'com.example.taksimKapimda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj3R1ZeEdyxEr-5us6NdAiK0IyvhjHQeE',
    appId: '1:183514899423:ios:ee4bebddca1207295e9a6a',
    messagingSenderId: '183514899423',
    projectId: 'taksikapim',
    databaseURL: 'https://taksikapim-default-rtdb.firebaseio.com',
    storageBucket: 'taksikapim.firebasestorage.app',
    iosBundleId: 'com.example.taksimKapimda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtYJ5qIuL_BafjKXZpn8A8U7dLFYg1n28',
    appId: '1:183514899423:web:dd54f0889e7128065e9a6a',
    messagingSenderId: '183514899423',
    projectId: 'taksikapim',
    authDomain: 'taksikapim.firebaseapp.com',
    databaseURL: 'https://taksikapim-default-rtdb.firebaseio.com',
    storageBucket: 'taksikapim.firebasestorage.app',
  );
}
